=== opencobra/cobrapy/src/cobra/io/schema_v1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "COBRA",
  "description": "JSON representation of COBRA model",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "default": "1"
    },
    "reactions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "metabolites": {
            "type": "object",
            "patternProperties": {
              ".*": {
                "type": "number"
              }
            }
          },
          "gene_reaction_rule": {
            "type": "string"
          },
          "lower_bound": {
            "type": "number"
          },
          "upper_bound": {
            "type": "number"
          },
          "objective_coefficient": {
            "type": "number",
            "default": 0
          },
          "subsystem": {
            "type": "string"
          },
          "notes": {
            "type": "object"
          },
          "annotation": {
            "type": "object"
          }
        },
        "required": [
          "id",
          "name",
          "metabolites",
          "lower_bound",
          "upper_bound",
          "gene_reaction_rule"
        ],
        "additionalProperties": false
      }
    },
    "metabolites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "compartment": {
            "type": "string",
            "pattern": "[a-z]{1,2}"
          },
          "charge": {
            "type": "integer"
          },
          "formula": {
            "type": "string"
          },
          "_bound": {
            "type": "number",
            "default": 0
          },
          "notes": {
            "type": "object"
          },
          "annotation": {
            "type": "object"
          }
        },
        "required": [
          "id",
          "name",
          "compartment"
        ],
        "additionalProperties": false
      }
    },
    "genes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "notes": {
            "type": "object"
          },
          "annotation": {
            "type": "object"
          }
        },
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "compartments": {
      "type": "object",
      "patternProperties": {
        "[a-z]{1,2}": {
          "type": "string"
        }
      }
    },
    "notes": {
      "type": "object"
    },
    "annotation": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "reactions",
    "metabolites",
    "genes"
  ],
  "additionalProperties": true
}

=== opencobra/cobrapy/tests/data/e_coli_core.json
{
"metabolites":[
{
"id":"glc__D_e",
"name":"D-Glucose",
"compartment":"e",
"charge":0,
"formula":"C6H12O6",
"notes":{
"original_bigg_ids":[
"glc_D_e"
]
},
"annotation":{
"bigg.metabolite":[
"glc__D"
],
"biocyc":[
"META:Glucopyranose"
],
"chebi":[
"CHEBI:12965",
"CHEBI:20999",
"CHEBI:4167",
"CHEBI:17634"
],
"hmdb":[
"HMDB00122",
"HMDB06564"
],
"inchi_key":[
"WQZGKKKJIJFFOK-GASJEMHNSA-N"
],
"kegg.compound":[
"C00031"
],
"kegg.drug":[
"D00009"
],
"metanetx.chemical":[
"MNXM41"
],
"sabiork":[
"1406",
"1407"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd26821",
"cpd00027"
]
}
},
{
"id":"gln__L_c",
"name":"L-Glutamine",
"compartment":"c",
"charge":0,
"formula":"C5H10N2O3",
"notes":{
"original_bigg_ids":[
"gln_L_c"
]
},
"annotation":{
"bigg.metabolite":[
"gln__L"
],
"biocyc":[
"META:GLN"
],
"chebi":[
"CHEBI:42943",
"CHEBI:42899",
"CHEBI:32679",
"CHEBI:32678",
"CHEBI:58359",
"CHEBI:28300",
"CHEBI:42812",
"CHEBI:13110",
"CHEBI:18050",
"CHEBI:32666",
"CHEBI:6227",
"CHEBI:32665",
"CHEBI:21308",
"CHEBI:42814",
"CHEBI:5432",
"CHEBI:24316"
],
"hmdb":[
"HMDB00641"
],
"inchi_key":[
"ZDXPYRJPNDTMRX-VKHMYHEASA-N"
],
"kegg.compound":[
"C00064",
"C00303"
],
"kegg.drug":[
"D00015"
],
"metanetx.chemical":[
"MNXM37"
],
"reactome.compound":[
"113522",
"212615",
"29472"
],
"sabiork":[
"2011",
"74"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00253",
"cpd00053"
]
}
},
{
"id":"gln__L_e",
"name":"L-Glutamine",
"compartment":"e",
"charge":0,
"formula":"C5H10N2O3",
"notes":{
"original_bigg_ids":[
"gln_L_e"
]
},
"annotation":{
"bigg.metabolite":[
"gln__L"
],
"biocyc":[
"META:GLN"
],
"chebi":[
"CHEBI:42943",
"CHEBI:42899",
"CHEBI:32679",
"CHEBI:32678",
"CHEBI:58359",
"CHEBI:28300",
"CHEBI:42812",
"CHEBI:13110",
"CHEBI:18050",
"CHEBI:32666",
"CHEBI:6227",
"CHEBI:32665",
"CHEBI:21308",
"CHEBI:42814",
"CHEBI:5432",
"CHEBI:24316"
],
"hmdb":[
"HMDB00641"
],
"inchi_key":[
"ZDXPYRJPNDTMRX-VKHMYHEASA-N"
],
"kegg.compound":[
"C00064",
"C00303"
],
"kegg.drug":[
"D00015"
],
"metanetx.chemical":[
"MNXM37"
],
"reactome.compound":[
"113522",
"212615",
"29472"
],
"sabiork":[
"2011",
"74"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00253",
"cpd00053"
]
}
},
{
"id":"glu__L_c",
"name":"L-Glutamate",
"compartment":"c",
"charge":-1,
"formula":"C5H8NO4",
"notes":{
"original_bigg_ids":[
"glu_L_c"
]
},
"annotation":{
"bigg.metabolite":[
"glu__L"
],
"biocyc":[
"META:Glutamates",
"META:GLT"
],
"chebi":[
"CHEBI:76051",
"CHEBI:21301",
"CHEBI:29985",
"CHEBI:42825",
"CHEBI:29987",
"CHEBI:18237",
"CHEBI:24314",
"CHEBI:16015",
"CHEBI:13107",
"CHEBI:5431",
"CHEBI:21304",
"CHEBI:6224",
"CHEBI:14321",
"CHEBI:29988"
],
"hmdb":[
"HMDB00148",
"HMDB60475"
],
"inchi_key":[
"WHUUTDBJXJRKMK-VKHMYHEASA-M"
],
"kegg.compound":[
"C00025",
"C00302"
],
"kegg.drug":[
"D00007",
"D04341"
],
"metanetx.chemical":[
"MNXM89557"
],
"reactome.compound":[
"428614",
"29404",
"113552",
"210382"
],
"sabiork":[
"73",
"2010"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd27177",
"cpd00023",
"cpd19002"
]
}
},
{
"id":"glu__L_e",
"name":"L-Glutamate",
"compartment":"e",
"charge":-1,
"formula":"C5H8NO4",
"notes":{
"original_bigg_ids":[
"glu_L_e"
]
},
"annotation":{
"bigg.metabolite":[
"glu__L"
],
"biocyc":[
"META:Glutamates",
"META:GLT"
],
"chebi":[
"CHEBI:76051",
"CHEBI:21301",
"CHEBI:29985",
"CHEBI:42825",
"CHEBI:29987",
"CHEBI:18237",
"CHEBI:24314",
"CHEBI:16015",
"CHEBI:13107",
"CHEBI:5431",
"CHEBI:21304",
"CHEBI:6224",
"CHEBI:14321",
"CHEBI:29988"
],
"hmdb":[
"HMDB00148",
"HMDB60475"
],
"inchi_key":[
"WHUUTDBJXJRKMK-VKHMYHEASA-M"
],
"kegg.compound":[
"C00025",
"C00302"
],
"kegg.drug":[
"D00007",
"D04341"
],
"metanetx.chemical":[
"MNXM89557"
],
"reactome.compound":[
"428614",
"29404",
"113552",
"210382"
],
"sabiork":[
"73",
"2010"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd27177",
"cpd00023",
"cpd19002"
]
}
},
{
"id":"glx_c",
"name":"Glyoxylate",
"compartment":"c",
"charge":-1,
"formula":"C2H1O3",
"notes":{
"original_bigg_ids":[
"glx_c"
]
},
"annotation":{
"bigg.metabolite":[
"glx"
],
"biocyc":[
"META:GLYOX"
],
"chebi":[
"CHEBI:24420",
"CHEBI:36655",
"CHEBI:14368",
"CHEBI:24421",
"CHEBI:42767",
"CHEBI:16891",
"CHEBI:35977",
"CHEBI:5509"
],
"envipath":[
"32de3cf4-e3e6-4168-956e-32fa5ddb0ce1/compound/cdffdb1a-3322-4cc1-9171-d857bfaa198a",
"4fd7f3e0-dd25-43ac-9453-dda3e52396e4/compound/aecbda66-6e98-4c11-aeaf-6a072f4f963c",
"5882df9c-dae1-4d80-a40e-db4724271456/compound/9dc0aa3b-447a-4b5d-8157-501b036f9626",
"650babc9-9d68-4b73-9332-11972ca26f7b/compound/43b74f4f-bc8a-4b8b-b587-c97d8e9eed48"
],
"hmdb":[
"HMDB00119"
],
"inchi_key":[
"HHLFWLYXYJOTON-UHFFFAOYSA-M"
],
"kegg.compound":[
"C00048"
],
"metanetx.chemical":[
"MNXM69"
],
"reactome.compound":[
"904849",
"389678"
],
"sabiork":[
"1838"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00040"
]
}
},
{
"id":"h2o_c",
"name":"H2O H2O",
"compartment":"c",
"charge":0,
"formula":"H2O",
"notes":{
"original_bigg_ids":[
"h2o_c"
]
},
"annotation":{
"bigg.metabolite":[
"h2o"
],
"biocyc":[
"META:CPD-15815",
"META:OXONIUM",
"META:HYDROXYL-GROUP",
"META:WATER",
"META:OH"
],
"chebi":[
"CHEBI:13352",
"CHEBI:30490",
"CHEBI:43228",
"CHEBI:33813",
"CHEBI:44292",
"CHEBI:44641",
"CHEBI:27313",
"CHEBI:42043",
"CHEBI:44819",
"CHEBI:29356",
"CHEBI:5594",
"CHEBI:10743",
"CHEBI:15377",
"CHEBI:42857",
"CHEBI:13365",
"CHEBI:29412",
"CHEBI:16234",
"CHEBI:13419",
"CHEBI:5585",
"CHEBI:44701"
],
"envipath":[
"650babc9-9d68-4b73-9332-11972ca26f7b/compound/799908db-b8c9-4982-86cb-1f225e2ad08c",
"650babc9-9d68-4b73-9332-11972ca26f7b/compound/e7f34a8e-cded-4793-b6d5-792335b38636",
"5882df9c-dae1-4d80-a40e-db4724271456/compound/969d0227-3069-4e44-9525-7ae7bad84170"
],
"hmdb":[
"HMDB02111",
"HMDB01039"
],
"inchi_key":[
"XLYOFNOQVPJJNP-UHFFFAOYSA-N"
],
"kegg.compound":[
"C00001",
"C01328"
],
"kegg.drug":[
"D00001",
"D06322"
],
"metanetx.chemical":[
"MNXM2"
],
"reactome.compound":[
"113521",
"141343",
"2022884",
"5278291",
"29356",
"189422",
"5668574",
"5693747",
"109276",
"113519",
"1605715",
"8851517",
"113518",
"351603"
],
"sabiork":[
"40"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd27222",
"cpd00001",
"cpd15275"
]
}
},
{
"id":"h2o_e",
"name":"H2O H2O",
"compartment":"e",
"charge":0,
"formula":"H2O",
"notes":{
"original_bigg_ids":[
"h2o_e"
]
},
"annotation":{
"bigg.metabolite":[
"h2o"
],
"biocyc":[
"META:CPD-15815",
"META:OXONIUM",
"META:HYDROXYL-GROUP",
"META:WATER",
"META:OH"
],
"chebi":[
"CHEBI:13352",
"CHEBI:30490",
"CHEBI:43228",
"CHEBI:33813",
"CHEBI:44292",
"CHEBI:44641",
"CHEBI:27313",
"CHEBI:42043",
"CHEBI:44819",
"CHEBI:29356",
"CHEBI:5594",
"CHEBI:10743",
"CHEBI:15377",
"CHEBI:42857",
"CHEBI:13365",
"CHEBI:29412",
"CHEBI:16234",
"CHEBI:13419",
"CHEBI:5585",
"CHEBI:44701"
],
"envipath":[
"650babc9-9d68-4b73-9332-11972ca26f7b/compound/799908db-b8c9-4982-86cb-1f225e2ad08c",
"650babc9-9d68-4b73-9332-11972ca26f7b/compound/e7f34a8e-cded-4793-b6d5-792335b38636",
"5882df9c-dae1-4d80-a40e-db4724271456/compound/969d0227-3069-4e44-9525-7ae7bad84170"
],
"hmdb":[
"HMDB02111",
"HMDB01039"
],
"inchi_key":[
"XLYOFNOQVPJJNP-UHFFFAOYSA-N"
],
"kegg.compound":[
"C00001",
"C01328"
],
"kegg.drug":[
"D00001",
"D06322"
],
"metanetx.chemical":[
"MNXM2"
],
"reactome.compound":[
"113521",
"141343",
"2022884",
"5278291",
"29356",
"189422",
"5668574",
"5693747",
"109276",
"113519",
"1605715",
"8851517",
"113518",
"351603"
],
"sabiork":[
"40"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd27222",
"cpd00001",
"cpd15275"
]
}
},
{
"id":"h_c",
"name":"H+",
"compartment":"c",
"charge":1,
"formula":"H",
"notes":{
"original_bigg_ids":[
"h_c"
]
},
"annotation":{
"bigg.metabolite":[
"h"
],
"biocyc":[
"META:PROTON"
],
"chebi":[
"CHEBI:5584",
"CHEBI:13357",
"CHEBI:15378",
"CHEBI:10744"
],
"hmdb":[
"HMDB59597"
],
"inchi_key":[
"GPRLSGONYQIRFK-UHFFFAOYSA-N"
],
"kegg.compound":[
"C00080"
],
"metanetx.chemical":[
"MNXM1"
],
"reactome.compound":[
"2000349",
"425978",
"74722",
"428040",
"427899",
"428548",
"156540",
"70106",
"425969",
"1132304",
"5668577",
"1470067",
"163953",
"193465",
"113529",
"351626",
"425999",
"194688",
"374900",
"2872447",
"372511"
],
"sabiork":[
"39"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00067"
]
}
},
{
"id":"h_e",
"name":"H+",
"compartment":"e",
"charge":1,
"formula":"H",
"notes":{
"original_bigg_ids":[
"h_e"
]
},
"annotation":{
"bigg.metabolite":[
"h"
],
"biocyc":[
"META:PROTON"
],
"chebi":[
"CHEBI:5584",
"CHEBI:13357",
"CHEBI:15378",
"CHEBI:10744"
],
"hmdb":[
"HMDB59597"
],
"inchi_key":[
"GPRLSGONYQIRFK-UHFFFAOYSA-N"
],
"kegg.compound":[
"C00080"
],
"metanetx.chemical":[
"MNXM1"
],
"reactome.compound":[
"2000349",
"425978",
"74722",
"428040",
"427899",
"428548",
"156540",
"70106",
"425969",
"1132304",
"5668577",
"1470067",
"163953",
"193465",
"113529",
"351626",
"425999",
"194688",
"374900",
"2872447",
"372511"
],
"sabiork":[
"39"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00067"
]
}
},
{
"id":"icit_c",
"name":"Isocitrate",
"compartment":"c",
"charge":-3,
"formula":"C6H5O7",
"notes":{
"original_bigg_ids":[
"icit_c"
]
},
"annotation":{
"bigg.metabolite":[
"icit"
],
"chebi":[
"CHEBI:16087",
"CHEBI:36454",
"CHEBI:5998",
"CHEBI:24886",
"CHEBI:36453",
"CHEBI:14465",
"CHEBI:30887",
"CHEBI:24884"
],
"hmdb":[
"HMDB00193"
],
"inchi_key":[
"ODBLHEXUDAPZAU-UHFFFAOYSA-K"
],
"kegg.compound":[
"C00311"
],
"metanetx.chemical":[
"MNXM89661"
],
"sabiork":[
"2013"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00260"
]
}
},
{
"id":"lac__D_c",
"name":"D-Lactate",
"compartment":"c",
"charge":-1,
"formula":"C3H5O3",
"notes":{
"original_bigg_ids":[
"lac_D_c"
]
},
"annotation":{
"bigg.metabolite":[
"lac__D"
],
"biocyc":[
"META:D-LACTATE"
],
"chebi":[
"CHEBI:16004",
"CHEBI:341",
"CHEBI:18684",
"CHEBI:43701",
"CHEBI:11001",
"CHEBI:42111",
"CHEBI:42105"
],
"hmdb":[
"HMDB01311",
"HMDB00171"
],
"inchi_key":[
"JVTAAEKCZFNVCJ-UWTATZPHSA-M"
],
"kegg.compound":[
"C00256"
],
"metanetx.chemical":[
"MNXM285"
],
"sabiork":[
"1997",
"2284"
],
"sbo":"SBO:0000247",
"seed.compound":[
"cpd00221"
]
}
},
{
"id":"lac__D_e",
"name":"D-Lactate",
"compartment":"e",
"charge":-1,
"formula":"C3H5O3",
"notes":{
"original_bigg_ids":[
