=== opencobra/cobrapy/src/cobra/io/schema_v2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "COBRA",
  "description": "JSON representation of COBRA model",
  "definitions": {
    "annotation": {
      "type": "object",
      "properties": {
        "sbo": {
          "type": "string"
        },
        "cvterms": {
          "type": "object",
          "additionalProperties": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "resources": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "nested_data": {
                  "$ref": "#/definitions/annotation"
                }
              }
            }
          }
        },
        "history": {
          "type": "object",
          "properties": {
            "creators": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  },
                  "organization_name": {
                    "type": "string"
                  }
                },
                "required": [
                  "first_name",
                  "last_name"
                ],
                "additionalProperties": false
              }
            },
            "created_date": {
              "type": "string",
              "format": "date-time"
            },
            "modified_dates": {
              "type": "array",
              "items": {
                "type": "string",
                "format": "date-time"
              }
            }
          },
          "required": [
            "creators",
            "created_date",
            "modified_dates"
          ],
          "additionalProperties": false
        },
        "listofkeyvalue": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
              },
              "name": {
                "type": "string"
              },
              "key": {
                "type": "string"
              },
              "value": {
                "type": "string"
              },
              "uri": {
                "type": "string"
              }
            },
            "required": [
              "key"
            ],
            "additionalProperties": false
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "default": "1"
    },
    "reactions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
          },
          "name": {
            "type": "string"
          },
          "metabolites": {
            "type": "object",
            "patternProperties": {
              ".*": {
                "type": "number"
              }
            }
          },
          "gene_reaction_rule": {
            "type": "string"
          },
          "lower_bound": {
            "type": "number"
          },
          "upper_bound": {
            "type": "number"
          },
          "objective_coefficient": {
            "type": "number",
            "default": 0
          },
          "subsystem": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          },
          "annotation": {
            "$ref": "#/definitions/annotation"
          }
        },
        "required": [
          "id",
          "name",
          "metabolites",
          "lower_bound",
          "upper_bound",
          "gene_reaction_rule"
        ],
        "additionalProperties": false
      }
    },
    "metabolites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
          },
          "name": {
            "type": "string"
          },
          "compartment": {
            "type": "string",
            "pattern": "[a-z]{1,2}"
          },
          "charge": {
            "type": "integer"
          },
          "formula": {
            "type": "string"
          },
          "_bound": {
            "type": "number",
            "default": 0
          },
          "notes": {
            "type": "string"
          },
          "annotation": {
            "$ref": "#/definitions/annotation"
          }
        },
        "required": [
          "id",
          "name",
          "compartment"
        ],
        "additionalProperties": false
      }
    },
    "genes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
          },
          "name": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          },
          "annotation": {
            "$ref": "#/definitions/annotation"
          }
        },
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false
      }
    },
    "compartments": {
      "type": "object",
      "patternProperties": {
        "[a-z]{1,2}": {
          "type": "string"
        }
      }
    },
    "groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
          },
          "name": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          },
          "annotation": {
            "$ref": "#/definitions/annotation"
          },
          "kind": {
            "type": "string",
            "enum": ["collection", "classification", "partonomy"]
          },
          "members": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "idRef": {
                  "type": "string",
                  "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": ["idRef", "type"]
            }
          }
        },
        "required": ["kind", "members"]
      }
    },
    "user_defined_constraints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
          },
          "name": {
            "type": "string"
          },
          "lower_bound": {
            "type": "number"
          },
          "upper_bound": {
            "type": "number"
          },
          "constraint_comps": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "pattern": "^[a-zA-Z|_][a-zA-Z0-9_]*$"
                },
                "name": {
                  "type": "string"
                },
                "coefficient": {
                  "type": "number"
                },
                "variable": {
                  "type": "string"
                },
                "variable_type": {
                  "type": "string",
                  "enum": ["linear", "quadratic"]
                },
                "notes": {
                  "type": "string"
                },
                "annotation": {
                  "$ref": "#/definitions/annotation"
                }
              },
              "required": ["variable"],
              "additionalProperties": false
            }
          },
          "notes": {
            "type": "string"
          },
          "annotation": {
            "$ref": "#/definitions/annotation"
          }
        },
        "required": ["lower_bound", "upper_bound", "constraint_comps"],
        "additionalProperties": false
      }
    },
    "notes": {
      "type": "string"
    },
    "annotation": {
      "$ref": "#/definitions/annotation"
    }
  },
  "required": [
    "id",
    "reactions",
    "metabolites",
    "genes"
  ],
  "additionalProperties": true
}

=== opencobra/cobrapy/src/cobra/data/mini.json
{
    "compartments": {
        "c": "cytosol",
        "e": "extracellular"
    },
    "genes": [
        {
            "id": "G_b0755",
            "name": "gpmA"
        },
        {
            "id": "G_b0875",
            "name": "aqpZ"
        },
        {
            "id": "G_b1101",
            "name": "ptsG"
        },
        {
            "id": "G_b1380",
            "name": "ldhA"
        },
        {
            "id": "G_b1621",
            "name": "malX"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/ncbiprotein/1208453",
                                "http://identifiers.org/ncbiprotein/1652654"
                            ]
                        }
                    ]
                }
            },
            "id": "G_b1676",
            "name": "pykF"
        },
        {
            "id": "G_b1723",
            "name": "pfkB"
        },
        {
            "id": "G_b1773",
            "name": "ydjI"
        },
        {
            "id": "G_b1779",
            "name": "gapA"
        },
        {
            "id": "G_b1817",
            "name": "manX"
        },
        {
            "id": "G_b1818",
            "name": "manY"
        },
        {
            "id": "G_b1819",
            "name": "manZ"
        },
        {
            "id": "G_b1854",
            "name": "pykA"
        },
        {
            "id": "G_b2097",
            "name": "fbaB"
        },
        {
            "id": "G_b2133",
            "name": "dld"
        },
        {
            "id": "G_b2415",
            "name": "ptsH"
        },
        {
            "id": "G_b2416",
            "name": "ptsI"
        },
        {
            "id": "G_b2417",
            "name": "crr"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/ncbiprotein/1653839"
                            ]
                        }
                    ]
                }
            },
            "id": "G_b2779",
            "name": "eno"
        },
        {
            "id": "G_b2925",
            "name": "fbaA"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/ncbiprotein/1653609"
                            ]
                        }
                    ]
                }
            },
            "id": "G_b2926",
            "name": "pgk"
        },
        {
            "id": "G_b2987",
            "name": "pitB"
        },
        {
            "id": "G_b3493",
            "name": "pitA"
        },
        {
            "id": "G_b3612",
            "name": "gpmM"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/ncbiprotein/1006614",
                                "http://identifiers.org/ncbiprotein/1651919"
                            ]
                        }
                    ]
                }
            },
            "id": "G_b3916",
            "name": "pfkA"
        },
        {
            "id": "G_b3919",
            "name": "tpiA"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/ncbiprotein/1653253"
                            ]
                        }
                    ]
                }
            },
            "id": "G_b4025",
            "name": "pgi"
        },
        {
            "id": "G_b4395",
            "name": "ytjC"
        },
        {
            "id": "G_s0001",
            "name": "G_s0001"
        }
    ],
    "groups": [],
    "id": "mini_textbook",
    "metabolites": [
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/bigg.metabolite/13dpg",
                                "http://identifiers.org/biocyc/DPG",
                                "http://identifiers.org/chebi/CHEBI:16001",
                                "http://identifiers.org/chebi/CHEBI:1658",
                                "http://identifiers.org/chebi/CHEBI:20189",
                                "http://identifiers.org/chebi/CHEBI:57604",
                                "http://identifiers.org/chebi/CHEBI:11881",
                                "http://identifiers.org/hmdb/HMDB01270",
                                "http://identifiers.org/kegg.compound/C00236",
                                "http://identifiers.org/pubchem.substance/3535",
                                "http://identifiers.org/reactome/REACT_29800",
                                "http://identifiers.org/seed.compound/cpd00203",
                                "http://identifiers.org/unipathway.compound/UPC00236"
                            ]
                        }
                    ]
                }
            },
            "charge": -4,
            "compartment": "c",
            "formula": "C3H4O10P2",
            "id": "M_13dpg_c",
            "name": "3-Phospho-D-glyceroyl phosphate"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/bigg.metabolite/2pg",
                                "http://identifiers.org/biocyc/2-PG",
                                "http://identifiers.org/chebi/CHEBI:1267",
                                "http://identifiers.org/chebi/CHEBI:58289",
                                "http://identifiers.org/chebi/CHEBI:17835",
                                "http://identifiers.org/chebi/CHEBI:21028",
                                "http://identifiers.org/chebi/CHEBI:11651",
                                "http://identifiers.org/chebi/CHEBI:12986",
                                "http://identifiers.org/chebi/CHEBI:24344",
                                "http://identifiers.org/chebi/CHEBI:39868",
                                "http://identifiers.org/hmdb/HMDB03391",
                                "http://identifiers.org/hmdb/HMDB00362",
                                "http://identifiers.org/kegg.compound/C00631",
                                "http://identifiers.org/pubchem.substance/3904",
                                "http://identifiers.org/reactome/REACT_30485",
                                "http://identifiers.org/seed.compound/cpd00482",
                                "http://identifiers.org/unipathway.compound/UPC00631"
                            ]
                        }
                    ]
                }
            },
            "charge": -3,
            "compartment": "c",
            "formula": "C3H4O7P",
            "id": "M_2pg_c",
            "name": "D-Glycerate 2-phosphate"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
                                "http://identifiers.org/bigg.metabolite/3pg",
                                "http://identifiers.org/biocyc/G3P",
                                "http://identifiers.org/chebi/CHEBI:40016",
                                "http://identifiers.org/chebi/CHEBI:58272",
                                "http://identifiers.org/chebi/CHEBI:57998",
                                "http://identifiers.org/chebi/CHEBI:11879",
                                "http://identifiers.org/chebi/CHEBI:1657",
                                "http://identifiers.org/chebi/CHEBI:1659",
                                "http://identifiers.org/chebi/CHEBI:17050",
                                "http://identifiers.org/chebi/CHEBI:21029",
                                "http://identifiers.org/chebi/CHEBI:11882",
                                "http://identifiers.org/chebi/CHEBI:11880",
                                "http://identifiers.org/chebi/CHEBI:12987",
                                "http://identifiers.org/chebi/CHEBI:17794",
                                "http://identifiers.org/chebi/CHEBI:24345",
                                "http://identifiers.org/hmdb/HMDB00807",
                                "http://identifiers.org/kegg.compound/C00197",
                                "http://identifiers.org/kegg.compound/C00597",
                                "http://identifiers.org/pubchem.substance/3497",
                                "http://identifiers.org/reactome/REACT_29728",
                                "http://identifiers.org/seed.compound/cpd00169",
                                "http://identifiers.org/unipathway.compound/UPC00597",
                                "http://identifiers.org/unipathway.compound/UPC00197"
                            ]
                        }
                    ]
                }
            },
            "charge": -3,
            "compartment": "c",
            "formula": "C3H4O7P",
            "id": "M_3pg_c",
            "name": "3-Phospho-D-glycerate"
        },
        {
            "annotation": {
                "standardized": {
                    "bqb_is": [
                        {
                            "resources": [
